sudo: required
services: 
  - docker

before_install:
  - docker build -t hello/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true hello/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: elasticbeanstalk-us-east-2-682547592010
  bucket_path: "docker"

  on:
    branch: master

  access_key_id: AKIAZ52YBXNFJ3RR4AHM
  secret_access_key: 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

  
  #   access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY
  # secure: "$AWS_SECRET_KEY"
    




  # access_key_id: AKIAZ52YBXNFFMGRKROE
  # secret_access_key: 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