sudo: required
services: 
  - docker

before_install:
  - docker build -t hello/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true hello/frontend npm run test -- --coverage

deploy:
  provider: elasticbeantalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-east-2-682547592010
  bucket_path: "docker"

  on:
    branch: master
  access_key_id: AKIAZ52YBXNFACUQUV7V
  secret_access_key: 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

  
  #   access_key_id: $AWS_ACCESS_KEY
  # secret_access_key: $AWS_SECRET_KEY
  # secure: "$AWS_SECRET_KEY"
    


